export const CURRENT_COUTDOWN = 'CURRENT_COUTDOWN';
export const LOGIN = 'LOGIN';
export const REQUEST_API = 'REQUEST_API';
export const REQUEST_API_SUCESS = 'REQUEST_API_SUCESS';
export const REQUEST_API_ERROR = 'REQUEST_API_ERROR';
export const STOP_COUTDOWN = 'STOP_COUTDOWN';
export const RESTART_COUTDOWN = 'RESTART_COUTDOWN';
export const QUESTION_ANSWERED = 'REQUEST_API_ERROR';
