export const GAME_UPDATE_SCORE = 'GAME_UPDATE_SCORE';
export const GAME_UPDATE_ASSERT = 'GAME_UPDATE_ASSERT';

export const GAME_MATCH_RESET = 'GAME_MATCH_RESET';
export const GAME_MATCH_UPDATE = 'GAME_MATCH_UPDATE';
